# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registr.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(413, 596)
        MainWindow2.setMinimumSize(QtCore.QSize(413, 596))
        MainWindow2.setMaximumSize(QtCore.QSize(413, 596))
        MainWindow2.setStyleSheet("background-color: rgb(243, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 161, 181))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Photo/Ellipse 1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 0, 221, 111))
        self.label_2.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Photo/Ellipse 2.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 430, 131, 171))
        self.label_4.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Photo/Ellipse 4 (1).png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 510, 291, 91))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Photo/Ellipse 3circle_entrance_three.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButtonVchod = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonVchod.setGeometry(QtCore.QRect(20, 410, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonVchod.setFont(font)
        self.pushButtonVchod.setStyleSheet("border-radius: 20px;  \n"
"background-color: rgb(252, 249, 249);\n"
"font: 75 16pt \"Arial\";\n"
"color: rgb(68, 64, 64);")
        self.pushButtonVchod.setObjectName("pushButtonVchod")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 170, 221, 51))
        self.label_5.setStyleSheet("font: 28pt \"Arial\";\n"
"color: rgb(68, 64, 64);")
        self.label_5.setObjectName("label_5")
        self.pushButtonGo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGo.setGeometry(QtCore.QRect(240, 280, 61, 61))
        self.pushButtonGo.setStyleSheet("border-radius: 30px;  \n"
"font: 75 25pt \"Arial\";\n"
"background-color: rgb(59, 178, 245);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonGo.setObjectName("pushButtonGo")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 230, 271, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(252, 249, 249);\n"
"border-color: rgb(224, 218, 218);\n"
"border-radius: 8px;  ")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 270, 271, 41))
        self.lineEdit_2.setStyleSheet("background-color: rgb(252, 249, 249);\n"
"border-color: rgb(224, 218, 218);\n"
"border-radius: 8px;  ")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(0, 310, 271, 41))
        self.lineEdit_3.setStyleSheet("background-color: rgb(252, 249, 249);\n"
"border-color: rgb(224, 218, 218);\n"
"border-radius:8px;  ")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(0, 350, 271, 41))
        self.lineEdit_4.setStyleSheet("background-color: rgb(252, 249, 249);\n"
"border-color: rgb(224, 218, 218);\n"
"border-radius: 5px;  ")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pushButtonVchod.raise_()
        self.label_5.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.pushButtonGo.raise_()
        MainWindow2.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "Регистрация"))
        self.pushButtonVchod.setText(_translate("MainWindow2", "Вход"))
        self.label_5.setText(_translate("MainWindow2", "Регистрация"))
        self.pushButtonGo.setText(_translate("MainWindow2", "Go"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow2", "   Твое имя"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow2", "   Твой емеил"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow2", "   Твой пароль"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow2", "   Повторите пароль"))
